version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic: #compounding conditions
    enabled: true
    config:
      threshold: 4
  file-lines: #not counting empty lines
    enabled: true
    config:
      threshold: 200 #default 250
  method-complexity: #cognitive complexity
    enabled: true
    config:
      threshold: 5
  method-count: #of a class
    enabled: true
    config:
      threshold: 20
  method-lines: #of any function
    enabled: true
    config:
      threshold: 25
  nested-control-flow: #of if/else/switch
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
  identical-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.

plugins:
  bandit:
    enabled: true
  radon: 
    enabled: true
    config: 
      threshold: "A" #defaults to B

exclude_patterns:
- "Assets/"
- "config/"
- "db/"
- "dist/"
- "features/"
- "**/node_modules/"
- "script/"
- "**/spec/"
# - "**/test/"
- "**/tests/"
- "**/vendor/"